name 'laravel_project'
maintainer 'Mike Lawson'
maintainer_email 'mlawson1986@gmail.com'
license 'MIT'
description 'Installs/Configures laravel_project'
long_description 'Installs/Configures laravel_project'
version '0.1.0'
chef_version '>= 14.0'
supports 'ubuntu'
issues_url 'https://github.com/djzara/laravel_project/issues'
source_url 'https://github.com/djzara/laravel_project'
